volumes:
  go-minify-url:
    driver: local
    
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - go-minify-url:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - go-minify-url:/data/db
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - redis-server

  minify-url:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: minify-url
    restart: always
    ports:
      - "5001:8080"
    volumes:
      - go-minify-url:/go/src
    depends_on:
      - mongodb
    environment:
      - APP_ENV=docker